version: '3'
services:
  app:
    build: ./app
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app
      - gems:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
volumes:
  gems:
  node_modules:
